# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-25 07:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoProductos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('descripcion', models.CharField(max_length=1000)),
                ('foto', models.ImageField(null=True, upload_to='images')),
                ('activo', models.BooleanField(default=False)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoCatalogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_definido', models.FloatField()),
                ('cantidad_definida', models.IntegerField()),
                ('id_catalogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.CatalogoProductos')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.Producto')),
            ],
        ),
        migrations.CreateModel(
            name='TipoUnidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('abreviatura', models.CharField(max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='id_tipo_unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.TipoUnidad'),
        ),
    ]
