# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-12 20:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
        ('consumidor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total', models.FloatField()),
                ('cantidad_items', models.IntegerField()),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCarrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('id_carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consumidor.Carrito')),
                ('id_producto_catalogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.ProductoCatalogo')),
            ],
        ),
        migrations.AlterField(
            model_name='itemcompra',
            name='id_compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consumidor.Compra'),
        ),
    ]
