# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumidor', '0002_auto_20171112_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='fecha_hora',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
