# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-15 02:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productor', '0002_oferta_cantidad_aprobada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oferta',
            name='cantidad_aprobada',
        ),
    ]
