# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-02 08:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comun', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finca',
            name='municipio',
        ),
    ]
