# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 01:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estadooferta',
            old_name='description',
            new_name='descripcion',
        ),
    ]
