# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-12 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='cantidad_aprobada',
            field=models.IntegerField(default=0),
        ),
    ]
