# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-15 11:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comun', '0002_direccioncomprador'),
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('valor_total', models.FloatField()),
                ('fecha_entrega', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompraProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=100)),
                ('id_catalogoProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.CatalogoOferta')),
            ],
        ),
        migrations.CreateModel(
            name='MedioPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('id_comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comun.Usuario')),
            ],
        ),
        migrations.AddField(
            model_name='compra',
            name='id_compraProducto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consumidor.CompraProducto'),
        ),
        migrations.AddField(
            model_name='compra',
            name='id_comprador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comun.Usuario'),
        ),
    ]
